### PR TITLE
Merge branch 'sidebar+content' of https://github.com/andriihavryliak/…

### PR DESCRIPTION
**Pull request by vitaliipasiuta**
…Football.ua : made full column-top

### CODE REVIEW

**Comment by vitaliipasiuta** [comment]
screen shot 2018-07-06 at 10 36 50

**Comment by vitaliipasiuta** [comment]
Looks great, well done

**Comment by vitaliipasiuta** [comment]
just change background pls) little bit annoying ;) 
and this pink block. pls, make width fixed.

merge after

**Comment by vitaliipasiuta** [comment]
👍

**Comment by andriihavryliak** [comment]
I had to change height to fixed, not width) and background became white...width also was 1090px, but height was in percents

**Pull request merged**
